apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-player.fullname" . }}
  labels:
    {{- include "ai-player.labels" . | nindent 4 }}
spec:
  type: {{ .Values.aiPlayer.service.type }}
  ports:
    - port: {{ .Values.aiPlayer.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
      {{- if eq .Values.aiPlayer.service.type "NodePort" }}
      nodePort: {{ .Values.aiPlayer.service.nodePort }}
      {{- end }}
  selector:
    {{- include "ai-player.selectorLabels" . | nindent 4 }}
