# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/angzarr/examples/v1/components.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'io/angzarr/examples/v1/components.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from io.angzarr.v1 import options_pb2 as io_dot_angzarr_dot_v1_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'io/angzarr/examples/v1/components.proto\x12\x16io.angzarr.examples.v1\x1a\x1bio/angzarr/v1/options.proto\"F\n\rTableHandSaga:5\xa2\xbb\x18\x31\x08\x02\x12\x05table\x1a\x04hand* io.angzarr.examples.v1.DealCards\"$\n\rHandTableSaga:\x13\xa2\xbb\x18\x0f\x08\x02\x12\x04hand\x1a\x05table\"&\n\x0eHandPlayerSaga:\x14\xa2\xbb\x18\x10\x08\x02\x12\x04hand\x1a\x06player\"(\n\x0fTablePlayerSaga:\x15\xa2\xbb\x18\x11\x08\x02\x12\x05table\x1a\x06player\"(\n\x0fPlayerTableSaga:\x15\xa2\xbb\x18\x11\x08\x02\x12\x06player\x1a\x05tableB\xdb\x01\n\x1a\x63om.io.angzarr.examples.v1B\x0f\x43omponentsProtoP\x01Z1examples/v2/gen/io/angzarr/examples/v1;examplesv1\xa2\x02\x03IAE\xaa\x02\x16Io.Angzarr.Examples.V1\xca\x02\x16Io\\Angzarr\\Examples\\V1\xe2\x02\"Io\\Angzarr\\Examples\\V1\\GPBMetadata\xea\x02\x19Io::Angzarr::Examples::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.angzarr.examples.v1.components_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.io.angzarr.examples.v1B\017ComponentsProtoP\001Z1examples/v2/gen/io/angzarr/examples/v1;examplesv1\242\002\003IAE\252\002\026Io.Angzarr.Examples.V1\312\002\026Io\\Angzarr\\Examples\\V1\342\002\"Io\\Angzarr\\Examples\\V1\\GPBMetadata\352\002\031Io::Angzarr::Examples::V1'
  _globals['_TABLEHANDSAGA']._loaded_options = None
  _globals['_TABLEHANDSAGA']._serialized_options = b'\242\273\0301\010\002\022\005table\032\004hand* io.angzarr.examples.v1.DealCards'
  _globals['_HANDTABLESAGA']._loaded_options = None
  _globals['_HANDTABLESAGA']._serialized_options = b'\242\273\030\017\010\002\022\004hand\032\005table'
  _globals['_HANDPLAYERSAGA']._loaded_options = None
  _globals['_HANDPLAYERSAGA']._serialized_options = b'\242\273\030\020\010\002\022\004hand\032\006player'
  _globals['_TABLEPLAYERSAGA']._loaded_options = None
  _globals['_TABLEPLAYERSAGA']._serialized_options = b'\242\273\030\021\010\002\022\005table\032\006player'
  _globals['_PLAYERTABLESAGA']._loaded_options = None
  _globals['_PLAYERTABLESAGA']._serialized_options = b'\242\273\030\021\010\002\022\006player\032\005table'
  _globals['_TABLEHANDSAGA']._serialized_start=96
  _globals['_TABLEHANDSAGA']._serialized_end=166
  _globals['_HANDTABLESAGA']._serialized_start=168
  _globals['_HANDTABLESAGA']._serialized_end=204
  _globals['_HANDPLAYERSAGA']._serialized_start=206
  _globals['_HANDPLAYERSAGA']._serialized_end=244
  _globals['_TABLEPLAYERSAGA']._serialized_start=246
  _globals['_TABLEPLAYERSAGA']._serialized_end=286
  _globals['_PLAYERTABLESAGA']._serialized_start=288
  _globals['_PLAYERTABLESAGA']._serialized_end=328
# @@protoc_insertion_point(module_scope)
