# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/hand.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.examples.v1 import hand_pb2 as _m0

class HandAggregateHandler(Protocol):
    """Strict business seam for the HandAggregate aggregate."""

    def deal_cards(self, cmd: _m0.DealCards, state: _m0.HandState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def post_blind(self, cmd: _m0.PostBlind, state: _m0.HandState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def player_action(self, cmd: _m0.PlayerAction, state: _m0.HandState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def deal_community_cards(self, cmd: _m0.DealCommunityCards, state: _m0.HandState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def request_draw(self, cmd: _m0.RequestDraw, state: _m0.HandState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def reveal_cards(self, cmd: _m0.RevealCards, state: _m0.HandState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def award_pot(self, cmd: _m0.AwardPot, state: _m0.HandState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def apply_cards_dealt(self, state: _m0.HandState, event: _m0.CardsDealt) -> None: ...
    def apply_blind_posted(self, state: _m0.HandState, event: _m0.BlindPosted) -> None: ...
    def apply_action_taken(self, state: _m0.HandState, event: _m0.ActionTaken) -> None: ...
    def apply_betting_round_complete(self, state: _m0.HandState, event: _m0.BettingRoundComplete) -> None: ...
    def apply_community_cards_dealt(self, state: _m0.HandState, event: _m0.CommunityCardsDealt) -> None: ...
    def apply_draw_completed(self, state: _m0.HandState, event: _m0.DrawCompleted) -> None: ...
    def apply_showdown_started(self, state: _m0.HandState, event: _m0.ShowdownStarted) -> None: ...
    def apply_pot_awarded(self, state: _m0.HandState, event: _m0.PotAwarded) -> None: ...
    def apply_hand_complete(self, state: _m0.HandState, event: _m0.HandComplete) -> None: ...

def new_hand_aggregate_dispatch(handler: HandAggregateHandler) -> _az.AggregateDispatch:
    rebuilder = _az.Rebuilder(lambda: _m0.HandState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    def _apply_apply_cards_dealt(state, payload):
        event = _m0.CardsDealt()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_cards_dealt(state, event)
    rebuilder.apply("io.angzarr.examples.v1.CardsDealt", _apply_apply_cards_dealt)
    def _apply_apply_blind_posted(state, payload):
        event = _m0.BlindPosted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_blind_posted(state, event)
    rebuilder.apply("io.angzarr.examples.v1.BlindPosted", _apply_apply_blind_posted)
    def _apply_apply_action_taken(state, payload):
        event = _m0.ActionTaken()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_action_taken(state, event)
    rebuilder.apply("io.angzarr.examples.v1.ActionTaken", _apply_apply_action_taken)
    def _apply_apply_betting_round_complete(state, payload):
        event = _m0.BettingRoundComplete()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_betting_round_complete(state, event)
    rebuilder.apply("io.angzarr.examples.v1.BettingRoundComplete", _apply_apply_betting_round_complete)
    def _apply_apply_community_cards_dealt(state, payload):
        event = _m0.CommunityCardsDealt()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_community_cards_dealt(state, event)
    rebuilder.apply("io.angzarr.examples.v1.CommunityCardsDealt", _apply_apply_community_cards_dealt)
    def _apply_apply_draw_completed(state, payload):
        event = _m0.DrawCompleted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_draw_completed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.DrawCompleted", _apply_apply_draw_completed)
    def _apply_apply_showdown_started(state, payload):
        event = _m0.ShowdownStarted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_showdown_started(state, event)
    rebuilder.apply("io.angzarr.examples.v1.ShowdownStarted", _apply_apply_showdown_started)
    def _apply_apply_pot_awarded(state, payload):
        event = _m0.PotAwarded()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_pot_awarded(state, event)
    rebuilder.apply("io.angzarr.examples.v1.PotAwarded", _apply_apply_pot_awarded)
    def _apply_apply_hand_complete(state, payload):
        event = _m0.HandComplete()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_hand_complete(state, event)
    rebuilder.apply("io.angzarr.examples.v1.HandComplete", _apply_apply_hand_complete)
    dispatch = _az.AggregateDispatch("HandAggregate", "hand", rebuilder)
    def _on_deal_cards(cmd_any, state, cctx):
        cmd = _m0.DealCards()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.deal_cards(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.DealCards", _on_deal_cards)
    def _on_post_blind(cmd_any, state, cctx):
        cmd = _m0.PostBlind()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.post_blind(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.PostBlind", _on_post_blind)
    def _on_player_action(cmd_any, state, cctx):
        cmd = _m0.PlayerAction()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.player_action(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.PlayerAction", _on_player_action)
    def _on_deal_community_cards(cmd_any, state, cctx):
        cmd = _m0.DealCommunityCards()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.deal_community_cards(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.DealCommunityCards", _on_deal_community_cards)
    def _on_request_draw(cmd_any, state, cctx):
        cmd = _m0.RequestDraw()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.request_draw(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.RequestDraw", _on_request_draw)
    def _on_reveal_cards(cmd_any, state, cctx):
        cmd = _m0.RevealCards()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.reveal_cards(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.RevealCards", _on_reveal_cards)
    def _on_award_pot(cmd_any, state, cctx):
        cmd = _m0.AwardPot()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.award_pot(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.AwardPot", _on_award_pot)
    return dispatch

def register_hand_aggregate(router: _az.Router, handler: HandAggregateHandler) -> None:
    router.register_aggregate(new_hand_aggregate_dispatch(handler))

