# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/components.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.examples.v1 import hand_pb2 as _m0

class HandPlayerSagaHandler(Protocol):
    """Strict business seam for the HandPlayerSaga saga."""

    def pot_awarded(self, event: _m0.PotAwarded, dests: _az.Destinations) -> tuple[list[_t.CommandBook], list[_t.EventBook]]: ...

def new_hand_player_saga_dispatch(handler: HandPlayerSagaHandler) -> _az.SagaDispatch:
    dispatch = _az.SagaDispatch("HandPlayerSaga", "hand", targets=["player"])
    def _on_pot_awarded(event_any, dests):
        event = _m0.PotAwarded()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.pot_awarded(event, dests)
    dispatch.on_event("io.angzarr.examples.v1.PotAwarded", _on_pot_awarded)
    return dispatch

def register_hand_player_saga(router: _az.Router, handler: HandPlayerSagaHandler) -> None:
    router.register_saga(new_hand_player_saga_dispatch(handler))

