# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/components.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.examples.v1 import hand_pb2 as _m0

class HandTableSagaHandler(Protocol):
    """Strict business seam for the HandTableSaga saga."""

    def hand_complete(self, event: _m0.HandComplete, dests: _az.Destinations) -> tuple[list[_t.CommandBook], list[_t.EventBook]]: ...

def new_hand_table_saga_dispatch(handler: HandTableSagaHandler) -> _az.SagaDispatch:
    dispatch = _az.SagaDispatch("HandTableSaga", "hand", targets=["table"])
    def _on_hand_complete(event_any, dests):
        event = _m0.HandComplete()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.hand_complete(event, dests)
    dispatch.on_event("io.angzarr.examples.v1.HandComplete", _on_hand_complete)
    return dispatch

def register_hand_table_saga(router: _az.Router, handler: HandTableSagaHandler) -> None:
    router.register_saga(new_hand_table_saga_dispatch(handler))

