# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/hand.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.v1 import process_manager_pb2 as _pm
from io.angzarr.examples.v1 import hand_pb2 as _m0
from io.angzarr.examples.v1 import table_pb2 as _m1

class HandFlowProcessManagerHandler(Protocol):
    """Strict business seam for the HandFlowProcessManager process_manager."""

    def cards_dealt(self, event: _m0.CardsDealt, state: _m0.HandFlowState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def hand_complete(self, event: _m0.HandComplete, state: _m0.HandFlowState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def hand_started(self, event: _m1.HandStarted, state: _m0.HandFlowState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...

def new_hand_flow_process_manager_dispatch(handler: HandFlowProcessManagerHandler) -> _az.ProcessManagerDispatch:
    rebuilder = _az.Rebuilder(lambda: _m0.HandFlowState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    dispatch = _az.ProcessManagerDispatch("HandFlowProcessManager", "hand", rebuilder)
    def _on_cards_dealt(event_any, state, dests):
        event = _m0.CardsDealt()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.cards_dealt(event, state, dests)
    dispatch.on_event("hand", "io.angzarr.examples.v1.CardsDealt", _on_cards_dealt)
    def _on_hand_complete(event_any, state, dests):
        event = _m0.HandComplete()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.hand_complete(event, state, dests)
    dispatch.on_event("hand", "io.angzarr.examples.v1.HandComplete", _on_hand_complete)
    def _on_hand_started(event_any, state, dests):
        event = _m1.HandStarted()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.hand_started(event, state, dests)
    dispatch.on_event("table", "io.angzarr.examples.v1.HandStarted", _on_hand_started)
    return dispatch

def register_hand_flow_process_manager(router: _az.Router, handler: HandFlowProcessManagerHandler) -> None:
    router.register_process_manager(new_hand_flow_process_manager_dispatch(handler))

