# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/order_workflow.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.v1 import process_manager_pb2 as _pm
from io.angzarr.examples.v1 import order_workflow_pb2 as _m0

class OrderWorkflowProcessManagerHandler(Protocol):
    """Strict business seam for the OrderWorkflowProcessManager process_manager."""

    def order_created(self, event: _m0.OrderCreated, state: _m0.OrderWorkflowState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def inventory_reserved(self, event: _m0.InventoryReserved, state: _m0.OrderWorkflowState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def payment_received(self, event: _m0.PaymentReceived, state: _m0.OrderWorkflowState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...

def new_order_workflow_process_manager_dispatch(handler: OrderWorkflowProcessManagerHandler) -> _az.ProcessManagerDispatch:
    rebuilder = _az.Rebuilder(lambda: _m0.OrderWorkflowState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    dispatch = _az.ProcessManagerDispatch("OrderWorkflowProcessManager", "inventory", rebuilder)
    def _on_order_created(event_any, state, dests):
        event = _m0.OrderCreated()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.order_created(event, state, dests)
    dispatch.on_event("order", "io.angzarr.examples.v1.OrderCreated", _on_order_created)
    def _on_inventory_reserved(event_any, state, dests):
        event = _m0.InventoryReserved()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.inventory_reserved(event, state, dests)
    dispatch.on_event("inventory", "io.angzarr.examples.v1.InventoryReserved", _on_inventory_reserved)
    def _on_payment_received(event_any, state, dests):
        event = _m0.PaymentReceived()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.payment_received(event, state, dests)
    dispatch.on_event("payment", "io.angzarr.examples.v1.PaymentReceived", _on_payment_received)
    return dispatch

def register_order_workflow_process_manager(router: _az.Router, handler: OrderWorkflowProcessManagerHandler) -> None:
    router.register_process_manager(new_order_workflow_process_manager_dispatch(handler))

