# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/player.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.examples.v1 import player_pb2 as _m0

class PlayerAggregateHandler(Protocol):
    """Strict business seam for the PlayerAggregate aggregate."""

    def register_player(self, cmd: _m0.RegisterPlayer, state: _m0.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def deposit_funds(self, cmd: _m0.DepositFunds, state: _m0.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def withdraw_funds(self, cmd: _m0.WithdrawFunds, state: _m0.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def reserve_funds(self, cmd: _m0.ReserveFunds, state: _m0.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def release_funds(self, cmd: _m0.ReleaseFunds, state: _m0.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def deduct_reserved_funds(self, cmd: _m0.DeductReservedFunds, state: _m0.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def transfer_funds(self, cmd: _m0.TransferFunds, state: _m0.PlayerState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def apply_player_registered(self, state: _m0.PlayerState, event: _m0.PlayerRegistered) -> None: ...
    def apply_funds_deposited(self, state: _m0.PlayerState, event: _m0.FundsDeposited) -> None: ...
    def apply_funds_withdrawn(self, state: _m0.PlayerState, event: _m0.FundsWithdrawn) -> None: ...
    def apply_funds_reserved(self, state: _m0.PlayerState, event: _m0.FundsReserved) -> None: ...
    def apply_funds_released(self, state: _m0.PlayerState, event: _m0.FundsReleased) -> None: ...
    def apply_funds_transferred(self, state: _m0.PlayerState, event: _m0.FundsTransferred) -> None: ...
    def apply_funds_deducted(self, state: _m0.PlayerState, event: _m0.FundsDeducted) -> None: ...

def new_player_aggregate_dispatch(handler: PlayerAggregateHandler) -> _az.AggregateDispatch:
    rebuilder = _az.Rebuilder(lambda: _m0.PlayerState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    def _apply_apply_player_registered(state, payload):
        event = _m0.PlayerRegistered()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_player_registered(state, event)
    rebuilder.apply("io.angzarr.examples.v1.PlayerRegistered", _apply_apply_player_registered)
    def _apply_apply_funds_deposited(state, payload):
        event = _m0.FundsDeposited()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_funds_deposited(state, event)
    rebuilder.apply("io.angzarr.examples.v1.FundsDeposited", _apply_apply_funds_deposited)
    def _apply_apply_funds_withdrawn(state, payload):
        event = _m0.FundsWithdrawn()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_funds_withdrawn(state, event)
    rebuilder.apply("io.angzarr.examples.v1.FundsWithdrawn", _apply_apply_funds_withdrawn)
    def _apply_apply_funds_reserved(state, payload):
        event = _m0.FundsReserved()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_funds_reserved(state, event)
    rebuilder.apply("io.angzarr.examples.v1.FundsReserved", _apply_apply_funds_reserved)
    def _apply_apply_funds_released(state, payload):
        event = _m0.FundsReleased()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_funds_released(state, event)
    rebuilder.apply("io.angzarr.examples.v1.FundsReleased", _apply_apply_funds_released)
    def _apply_apply_funds_transferred(state, payload):
        event = _m0.FundsTransferred()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_funds_transferred(state, event)
    rebuilder.apply("io.angzarr.examples.v1.FundsTransferred", _apply_apply_funds_transferred)
    def _apply_apply_funds_deducted(state, payload):
        event = _m0.FundsDeducted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_funds_deducted(state, event)
    rebuilder.apply("io.angzarr.examples.v1.FundsDeducted", _apply_apply_funds_deducted)
    dispatch = _az.AggregateDispatch("PlayerAggregate", "player", rebuilder)
    def _on_register_player(cmd_any, state, cctx):
        cmd = _m0.RegisterPlayer()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.register_player(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.RegisterPlayer", _on_register_player)
    def _on_deposit_funds(cmd_any, state, cctx):
        cmd = _m0.DepositFunds()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.deposit_funds(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.DepositFunds", _on_deposit_funds)
    def _on_withdraw_funds(cmd_any, state, cctx):
        cmd = _m0.WithdrawFunds()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.withdraw_funds(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.WithdrawFunds", _on_withdraw_funds)
    def _on_reserve_funds(cmd_any, state, cctx):
        cmd = _m0.ReserveFunds()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.reserve_funds(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ReserveFunds", _on_reserve_funds)
    def _on_release_funds(cmd_any, state, cctx):
        cmd = _m0.ReleaseFunds()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.release_funds(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ReleaseFunds", _on_release_funds)
    def _on_deduct_reserved_funds(cmd_any, state, cctx):
        cmd = _m0.DeductReservedFunds()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.deduct_reserved_funds(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.DeductReservedFunds", _on_deduct_reserved_funds)
    def _on_transfer_funds(cmd_any, state, cctx):
        cmd = _m0.TransferFunds()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.transfer_funds(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.TransferFunds", _on_transfer_funds)
    return dispatch

def register_player_aggregate(router: _az.Router, handler: PlayerAggregateHandler) -> None:
    router.register_aggregate(new_player_aggregate_dispatch(handler))

