# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/components.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.examples.v1 import player_pb2 as _m0

class PlayerTableSagaHandler(Protocol):
    """Strict business seam for the PlayerTableSaga saga."""

    def player_sitting_out(self, event: _m0.PlayerSittingOut, dests: _az.Destinations) -> tuple[list[_t.CommandBook], list[_t.EventBook]]: ...
    def player_returning_to_play(self, event: _m0.PlayerReturningToPlay, dests: _az.Destinations) -> tuple[list[_t.CommandBook], list[_t.EventBook]]: ...

def new_player_table_saga_dispatch(handler: PlayerTableSagaHandler) -> _az.SagaDispatch:
    dispatch = _az.SagaDispatch("PlayerTableSaga", "player", targets=["table"])
    def _on_player_sitting_out(event_any, dests):
        event = _m0.PlayerSittingOut()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.player_sitting_out(event, dests)
    dispatch.on_event("io.angzarr.examples.v1.PlayerSittingOut", _on_player_sitting_out)
    def _on_player_returning_to_play(event_any, dests):
        event = _m0.PlayerReturningToPlay()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.player_returning_to_play(event, dests)
    dispatch.on_event("io.angzarr.examples.v1.PlayerReturningToPlay", _on_player_returning_to_play)
    return dispatch

def register_player_table_saga(router: _az.Router, handler: PlayerTableSagaHandler) -> None:
    router.register_saga(new_player_table_saga_dispatch(handler))

