# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/reservation.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.v1 import process_manager_pb2 as _pm
from io.angzarr.examples.v1 import buy_in_pb2 as _m0
from io.angzarr.examples.v1 import rebuy_pb2 as _m1
from io.angzarr.examples.v1 import registration_pb2 as _m2
from io.angzarr.examples.v1 import reservation_pb2 as _m3
from io.angzarr.examples.v1 import tournament_pb2 as _m4

class ReservationProcessManagerHandler(Protocol):
    """Strict business seam for the ReservationProcessManager process_manager."""

    def buy_in_requested(self, event: _m0.BuyInRequested, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def buy_in_confirmed(self, event: _m0.BuyInConfirmed, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def buy_in_reservation_released(self, event: _m0.BuyInReservationReleased, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def player_seated(self, event: _m0.PlayerSeated, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def seating_rejected(self, event: _m0.SeatingRejected, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def rebuy_requested(self, event: _m1.RebuyRequested, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def rebuy_fee_confirmed(self, event: _m1.RebuyFeeConfirmed, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def rebuy_fee_released(self, event: _m1.RebuyFeeReleased, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def rebuy_chips_added(self, event: _m1.RebuyChipsAdded, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def registration_requested(self, event: _m2.RegistrationRequested, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def registration_fee_confirmed(self, event: _m2.RegistrationFeeConfirmed, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def registration_fee_released(self, event: _m2.RegistrationFeeReleased, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def tournament_player_enrolled(self, event: _m4.TournamentPlayerEnrolled, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def tournament_enrollment_rejected(self, event: _m4.TournamentEnrollmentRejected, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def rebuy_processed(self, event: _m4.RebuyProcessed, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def rebuy_denied(self, event: _m4.RebuyDenied, state: _m3.ReservationProcessManagerState, dests: _az.Destinations) -> _pm.ProcessManagerHandleResponse: ...
    def apply_buy_in_initiated(self, state: _m3.ReservationProcessManagerState, event: _m0.BuyInInitiated) -> None: ...
    def apply_buy_in_completed(self, state: _m3.ReservationProcessManagerState, event: _m0.BuyInCompleted) -> None: ...
    def apply_buy_in_failed(self, state: _m3.ReservationProcessManagerState, event: _m0.BuyInFailed) -> None: ...
    def apply_rebuy_initiated(self, state: _m3.ReservationProcessManagerState, event: _m1.RebuyInitiated) -> None: ...
    def apply_rebuy_completed(self, state: _m3.ReservationProcessManagerState, event: _m1.RebuyCompleted) -> None: ...
    def apply_rebuy_failed(self, state: _m3.ReservationProcessManagerState, event: _m1.RebuyFailed) -> None: ...
    def apply_registration_initiated(self, state: _m3.ReservationProcessManagerState, event: _m2.RegistrationInitiated) -> None: ...
    def apply_registration_completed(self, state: _m3.ReservationProcessManagerState, event: _m2.RegistrationCompleted) -> None: ...
    def apply_registration_failed(self, state: _m3.ReservationProcessManagerState, event: _m2.RegistrationFailed) -> None: ...

def new_reservation_process_manager_dispatch(handler: ReservationProcessManagerHandler) -> _az.ProcessManagerDispatch:
    rebuilder = _az.Rebuilder(lambda: _m3.ReservationProcessManagerState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    def _apply_apply_buy_in_initiated(state, payload):
        event = _m0.BuyInInitiated()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_buy_in_initiated(state, event)
    rebuilder.apply("io.angzarr.examples.v1.BuyInInitiated", _apply_apply_buy_in_initiated)
    def _apply_apply_buy_in_completed(state, payload):
        event = _m0.BuyInCompleted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_buy_in_completed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.BuyInCompleted", _apply_apply_buy_in_completed)
    def _apply_apply_buy_in_failed(state, payload):
        event = _m0.BuyInFailed()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_buy_in_failed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.BuyInFailed", _apply_apply_buy_in_failed)
    def _apply_apply_rebuy_initiated(state, payload):
        event = _m1.RebuyInitiated()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_rebuy_initiated(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RebuyInitiated", _apply_apply_rebuy_initiated)
    def _apply_apply_rebuy_completed(state, payload):
        event = _m1.RebuyCompleted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_rebuy_completed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RebuyCompleted", _apply_apply_rebuy_completed)
    def _apply_apply_rebuy_failed(state, payload):
        event = _m1.RebuyFailed()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_rebuy_failed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RebuyFailed", _apply_apply_rebuy_failed)
    def _apply_apply_registration_initiated(state, payload):
        event = _m2.RegistrationInitiated()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_registration_initiated(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RegistrationInitiated", _apply_apply_registration_initiated)
    def _apply_apply_registration_completed(state, payload):
        event = _m2.RegistrationCompleted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_registration_completed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RegistrationCompleted", _apply_apply_registration_completed)
    def _apply_apply_registration_failed(state, payload):
        event = _m2.RegistrationFailed()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_registration_failed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RegistrationFailed", _apply_apply_registration_failed)
    dispatch = _az.ProcessManagerDispatch("ReservationProcessManager", "player", rebuilder)
    def _on_buy_in_requested(event_any, state, dests):
        event = _m0.BuyInRequested()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.buy_in_requested(event, state, dests)
    dispatch.on_event("reservation", "io.angzarr.examples.v1.BuyInRequested", _on_buy_in_requested)
    def _on_buy_in_confirmed(event_any, state, dests):
        event = _m0.BuyInConfirmed()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.buy_in_confirmed(event, state, dests)
    dispatch.on_event("reservation", "io.angzarr.examples.v1.BuyInConfirmed", _on_buy_in_confirmed)
    def _on_buy_in_reservation_released(event_any, state, dests):
        event = _m0.BuyInReservationReleased()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.buy_in_reservation_released(event, state, dests)
    dispatch.on_event("reservation", "io.angzarr.examples.v1.BuyInReservationReleased", _on_buy_in_reservation_released)
    def _on_player_seated(event_any, state, dests):
        event = _m0.PlayerSeated()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.player_seated(event, state, dests)
    dispatch.on_event("table", "io.angzarr.examples.v1.PlayerSeated", _on_player_seated)
    def _on_seating_rejected(event_any, state, dests):
        event = _m0.SeatingRejected()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.seating_rejected(event, state, dests)
    dispatch.on_event("table", "io.angzarr.examples.v1.SeatingRejected", _on_seating_rejected)
    def _on_rebuy_requested(event_any, state, dests):
        event = _m1.RebuyRequested()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.rebuy_requested(event, state, dests)
    dispatch.on_event("reservation", "io.angzarr.examples.v1.RebuyRequested", _on_rebuy_requested)
    def _on_rebuy_fee_confirmed(event_any, state, dests):
        event = _m1.RebuyFeeConfirmed()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.rebuy_fee_confirmed(event, state, dests)
    dispatch.on_event("reservation", "io.angzarr.examples.v1.RebuyFeeConfirmed", _on_rebuy_fee_confirmed)
    def _on_rebuy_fee_released(event_any, state, dests):
        event = _m1.RebuyFeeReleased()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.rebuy_fee_released(event, state, dests)
    dispatch.on_event("reservation", "io.angzarr.examples.v1.RebuyFeeReleased", _on_rebuy_fee_released)
    def _on_rebuy_chips_added(event_any, state, dests):
        event = _m1.RebuyChipsAdded()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.rebuy_chips_added(event, state, dests)
    dispatch.on_event("table", "io.angzarr.examples.v1.RebuyChipsAdded", _on_rebuy_chips_added)
    def _on_registration_requested(event_any, state, dests):
        event = _m2.RegistrationRequested()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.registration_requested(event, state, dests)
    dispatch.on_event("reservation", "io.angzarr.examples.v1.RegistrationRequested", _on_registration_requested)
    def _on_registration_fee_confirmed(event_any, state, dests):
        event = _m2.RegistrationFeeConfirmed()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.registration_fee_confirmed(event, state, dests)
    dispatch.on_event("reservation", "io.angzarr.examples.v1.RegistrationFeeConfirmed", _on_registration_fee_confirmed)
    def _on_registration_fee_released(event_any, state, dests):
        event = _m2.RegistrationFeeReleased()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.registration_fee_released(event, state, dests)
    dispatch.on_event("reservation", "io.angzarr.examples.v1.RegistrationFeeReleased", _on_registration_fee_released)
    def _on_tournament_player_enrolled(event_any, state, dests):
        event = _m4.TournamentPlayerEnrolled()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.tournament_player_enrolled(event, state, dests)
    dispatch.on_event("tournament", "io.angzarr.examples.v1.TournamentPlayerEnrolled", _on_tournament_player_enrolled)
    def _on_tournament_enrollment_rejected(event_any, state, dests):
        event = _m4.TournamentEnrollmentRejected()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.tournament_enrollment_rejected(event, state, dests)
    dispatch.on_event("tournament", "io.angzarr.examples.v1.TournamentEnrollmentRejected", _on_tournament_enrollment_rejected)
    def _on_rebuy_processed(event_any, state, dests):
        event = _m4.RebuyProcessed()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.rebuy_processed(event, state, dests)
    dispatch.on_event("tournament", "io.angzarr.examples.v1.RebuyProcessed", _on_rebuy_processed)
    def _on_rebuy_denied(event_any, state, dests):
        event = _m4.RebuyDenied()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.rebuy_denied(event, state, dests)
    dispatch.on_event("tournament", "io.angzarr.examples.v1.RebuyDenied", _on_rebuy_denied)
    return dispatch

def register_reservation_process_manager(router: _az.Router, handler: ReservationProcessManagerHandler) -> None:
    router.register_process_manager(new_reservation_process_manager_dispatch(handler))

