# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/reservation.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.examples.v1 import buy_in_pb2 as _m0
from io.angzarr.examples.v1 import rebuy_pb2 as _m1
from io.angzarr.examples.v1 import registration_pb2 as _m2
from io.angzarr.examples.v1 import reservation_pb2 as _m3

class ReservationAggregateHandler(Protocol):
    """Strict business seam for the ReservationAggregate aggregate."""

    def initiate_buy_in(self, cmd: _m0.InitiateBuyIn, state: _m3.ReservationState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def confirm_buy_in(self, cmd: _m0.ConfirmBuyIn, state: _m3.ReservationState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def release_buy_in(self, cmd: _m0.ReleaseBuyIn, state: _m3.ReservationState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def initiate_rebuy(self, cmd: _m1.InitiateRebuy, state: _m3.ReservationState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def confirm_rebuy_fee(self, cmd: _m1.ConfirmRebuyFee, state: _m3.ReservationState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def release_rebuy_fee(self, cmd: _m1.ReleaseRebuyFee, state: _m3.ReservationState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def initiate_tournament_registration(self, cmd: _m2.InitiateTournamentRegistration, state: _m3.ReservationState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def confirm_registration_fee(self, cmd: _m2.ConfirmRegistrationFee, state: _m3.ReservationState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def release_registration_fee(self, cmd: _m2.ReleaseRegistrationFee, state: _m3.ReservationState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def apply_buy_in_requested(self, state: _m3.ReservationState, event: _m0.BuyInRequested) -> None: ...
    def apply_buy_in_confirmed(self, state: _m3.ReservationState, event: _m0.BuyInConfirmed) -> None: ...
    def apply_buy_in_reservation_released(self, state: _m3.ReservationState, event: _m0.BuyInReservationReleased) -> None: ...
    def apply_rebuy_requested(self, state: _m3.ReservationState, event: _m1.RebuyRequested) -> None: ...
    def apply_rebuy_fee_confirmed(self, state: _m3.ReservationState, event: _m1.RebuyFeeConfirmed) -> None: ...
    def apply_rebuy_fee_released(self, state: _m3.ReservationState, event: _m1.RebuyFeeReleased) -> None: ...
    def apply_registration_requested(self, state: _m3.ReservationState, event: _m2.RegistrationRequested) -> None: ...
    def apply_registration_fee_confirmed(self, state: _m3.ReservationState, event: _m2.RegistrationFeeConfirmed) -> None: ...
    def apply_registration_fee_released(self, state: _m3.ReservationState, event: _m2.RegistrationFeeReleased) -> None: ...

def new_reservation_aggregate_dispatch(handler: ReservationAggregateHandler) -> _az.AggregateDispatch:
    rebuilder = _az.Rebuilder(lambda: _m3.ReservationState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    def _apply_apply_buy_in_requested(state, payload):
        event = _m0.BuyInRequested()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_buy_in_requested(state, event)
    rebuilder.apply("io.angzarr.examples.v1.BuyInRequested", _apply_apply_buy_in_requested)
    def _apply_apply_buy_in_confirmed(state, payload):
        event = _m0.BuyInConfirmed()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_buy_in_confirmed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.BuyInConfirmed", _apply_apply_buy_in_confirmed)
    def _apply_apply_buy_in_reservation_released(state, payload):
        event = _m0.BuyInReservationReleased()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_buy_in_reservation_released(state, event)
    rebuilder.apply("io.angzarr.examples.v1.BuyInReservationReleased", _apply_apply_buy_in_reservation_released)
    def _apply_apply_rebuy_requested(state, payload):
        event = _m1.RebuyRequested()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_rebuy_requested(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RebuyRequested", _apply_apply_rebuy_requested)
    def _apply_apply_rebuy_fee_confirmed(state, payload):
        event = _m1.RebuyFeeConfirmed()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_rebuy_fee_confirmed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RebuyFeeConfirmed", _apply_apply_rebuy_fee_confirmed)
    def _apply_apply_rebuy_fee_released(state, payload):
        event = _m1.RebuyFeeReleased()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_rebuy_fee_released(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RebuyFeeReleased", _apply_apply_rebuy_fee_released)
    def _apply_apply_registration_requested(state, payload):
        event = _m2.RegistrationRequested()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_registration_requested(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RegistrationRequested", _apply_apply_registration_requested)
    def _apply_apply_registration_fee_confirmed(state, payload):
        event = _m2.RegistrationFeeConfirmed()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_registration_fee_confirmed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RegistrationFeeConfirmed", _apply_apply_registration_fee_confirmed)
    def _apply_apply_registration_fee_released(state, payload):
        event = _m2.RegistrationFeeReleased()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_registration_fee_released(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RegistrationFeeReleased", _apply_apply_registration_fee_released)
    dispatch = _az.AggregateDispatch("ReservationAggregate", "reservation", rebuilder)
    def _on_initiate_buy_in(cmd_any, state, cctx):
        cmd = _m0.InitiateBuyIn()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.initiate_buy_in(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.InitiateBuyIn", _on_initiate_buy_in)
    def _on_confirm_buy_in(cmd_any, state, cctx):
        cmd = _m0.ConfirmBuyIn()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.confirm_buy_in(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ConfirmBuyIn", _on_confirm_buy_in)
    def _on_release_buy_in(cmd_any, state, cctx):
        cmd = _m0.ReleaseBuyIn()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.release_buy_in(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ReleaseBuyIn", _on_release_buy_in)
    def _on_initiate_rebuy(cmd_any, state, cctx):
        cmd = _m1.InitiateRebuy()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.initiate_rebuy(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.InitiateRebuy", _on_initiate_rebuy)
    def _on_confirm_rebuy_fee(cmd_any, state, cctx):
        cmd = _m1.ConfirmRebuyFee()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.confirm_rebuy_fee(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ConfirmRebuyFee", _on_confirm_rebuy_fee)
    def _on_release_rebuy_fee(cmd_any, state, cctx):
        cmd = _m1.ReleaseRebuyFee()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.release_rebuy_fee(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ReleaseRebuyFee", _on_release_rebuy_fee)
    def _on_initiate_tournament_registration(cmd_any, state, cctx):
        cmd = _m2.InitiateTournamentRegistration()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.initiate_tournament_registration(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.InitiateTournamentRegistration", _on_initiate_tournament_registration)
    def _on_confirm_registration_fee(cmd_any, state, cctx):
        cmd = _m2.ConfirmRegistrationFee()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.confirm_registration_fee(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ConfirmRegistrationFee", _on_confirm_registration_fee)
    def _on_release_registration_fee(cmd_any, state, cctx):
        cmd = _m2.ReleaseRegistrationFee()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.release_registration_fee(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ReleaseRegistrationFee", _on_release_registration_fee)
    return dispatch

def register_reservation_aggregate(router: _az.Router, handler: ReservationAggregateHandler) -> None:
    router.register_aggregate(new_reservation_aggregate_dispatch(handler))

