# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/table.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.v1 import command_handler_pb2 as _ch
from io.angzarr.examples.v1 import buy_in_pb2 as _m0
from io.angzarr.examples.v1 import rebuy_pb2 as _m1
from io.angzarr.examples.v1 import table_pb2 as _m2

class TableAggregateHandler(Protocol):
    """Strict business seam for the TableAggregate aggregate."""

    def seat_player(self, cmd: _m0.SeatPlayer, state: _m2.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def add_rebuy_chips(self, cmd: _m1.AddRebuyChips, state: _m2.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def create_table(self, cmd: _m2.CreateTable, state: _m2.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def join_table(self, cmd: _m2.JoinTable, state: _m2.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def leave_table(self, cmd: _m2.LeaveTable, state: _m2.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def start_hand(self, cmd: _m2.StartHand, state: _m2.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def end_hand(self, cmd: _m2.EndHand, state: _m2.TableState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def apply_player_seated(self, state: _m2.TableState, event: _m0.PlayerSeated) -> None: ...
    def apply_seating_rejected(self, state: _m2.TableState, event: _m0.SeatingRejected) -> None: ...
    def apply_rebuy_chips_added(self, state: _m2.TableState, event: _m1.RebuyChipsAdded) -> None: ...
    def apply_table_created(self, state: _m2.TableState, event: _m2.TableCreated) -> None: ...
    def apply_player_joined(self, state: _m2.TableState, event: _m2.PlayerJoined) -> None: ...
    def apply_player_left(self, state: _m2.TableState, event: _m2.PlayerLeft) -> None: ...
    def apply_player_sat_out(self, state: _m2.TableState, event: _m2.PlayerSatOut) -> None: ...
    def apply_player_sat_in(self, state: _m2.TableState, event: _m2.PlayerSatIn) -> None: ...
    def apply_hand_started(self, state: _m2.TableState, event: _m2.HandStarted) -> None: ...
    def apply_hand_ended(self, state: _m2.TableState, event: _m2.HandEnded) -> None: ...
    def apply_chips_added(self, state: _m2.TableState, event: _m2.ChipsAdded) -> None: ...
    def on_deal_cards_rejected(self, n: _t.Notification, rejection: _t.RejectionNotification, state: _m2.TableState, cctx: _az.CommandContext) -> Optional[_ch.BusinessResponse]: ...

def new_table_aggregate_dispatch(handler: TableAggregateHandler) -> _az.AggregateDispatch:
    rebuilder = _az.Rebuilder(lambda: _m2.TableState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    def _apply_apply_player_seated(state, payload):
        event = _m0.PlayerSeated()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_player_seated(state, event)
    rebuilder.apply("io.angzarr.examples.v1.PlayerSeated", _apply_apply_player_seated)
    def _apply_apply_seating_rejected(state, payload):
        event = _m0.SeatingRejected()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_seating_rejected(state, event)
    rebuilder.apply("io.angzarr.examples.v1.SeatingRejected", _apply_apply_seating_rejected)
    def _apply_apply_rebuy_chips_added(state, payload):
        event = _m1.RebuyChipsAdded()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_rebuy_chips_added(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RebuyChipsAdded", _apply_apply_rebuy_chips_added)
    def _apply_apply_table_created(state, payload):
        event = _m2.TableCreated()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_table_created(state, event)
    rebuilder.apply("io.angzarr.examples.v1.TableCreated", _apply_apply_table_created)
    def _apply_apply_player_joined(state, payload):
        event = _m2.PlayerJoined()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_player_joined(state, event)
    rebuilder.apply("io.angzarr.examples.v1.PlayerJoined", _apply_apply_player_joined)
    def _apply_apply_player_left(state, payload):
        event = _m2.PlayerLeft()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_player_left(state, event)
    rebuilder.apply("io.angzarr.examples.v1.PlayerLeft", _apply_apply_player_left)
    def _apply_apply_player_sat_out(state, payload):
        event = _m2.PlayerSatOut()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_player_sat_out(state, event)
    rebuilder.apply("io.angzarr.examples.v1.PlayerSatOut", _apply_apply_player_sat_out)
    def _apply_apply_player_sat_in(state, payload):
        event = _m2.PlayerSatIn()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_player_sat_in(state, event)
    rebuilder.apply("io.angzarr.examples.v1.PlayerSatIn", _apply_apply_player_sat_in)
    def _apply_apply_hand_started(state, payload):
        event = _m2.HandStarted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_hand_started(state, event)
    rebuilder.apply("io.angzarr.examples.v1.HandStarted", _apply_apply_hand_started)
    def _apply_apply_hand_ended(state, payload):
        event = _m2.HandEnded()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_hand_ended(state, event)
    rebuilder.apply("io.angzarr.examples.v1.HandEnded", _apply_apply_hand_ended)
    def _apply_apply_chips_added(state, payload):
        event = _m2.ChipsAdded()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_chips_added(state, event)
    rebuilder.apply("io.angzarr.examples.v1.ChipsAdded", _apply_apply_chips_added)
    dispatch = _az.AggregateDispatch("TableAggregate", "table", rebuilder)
    def _on_seat_player(cmd_any, state, cctx):
        cmd = _m0.SeatPlayer()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.seat_player(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.SeatPlayer", _on_seat_player)
    def _on_add_rebuy_chips(cmd_any, state, cctx):
        cmd = _m1.AddRebuyChips()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.add_rebuy_chips(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.AddRebuyChips", _on_add_rebuy_chips)
    def _on_create_table(cmd_any, state, cctx):
        cmd = _m2.CreateTable()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.create_table(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.CreateTable", _on_create_table)
    def _on_join_table(cmd_any, state, cctx):
        cmd = _m2.JoinTable()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.join_table(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.JoinTable", _on_join_table)
    def _on_leave_table(cmd_any, state, cctx):
        cmd = _m2.LeaveTable()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.leave_table(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.LeaveTable", _on_leave_table)
    def _on_start_hand(cmd_any, state, cctx):
        cmd = _m2.StartHand()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.start_hand(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.StartHand", _on_start_hand)
    def _on_end_hand(cmd_any, state, cctx):
        cmd = _m2.EndHand()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.end_hand(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.EndHand", _on_end_hand)
    dispatch.on_rejected("io.angzarr.examples.v1.DealCards", handler.on_deal_cards_rejected)
    return dispatch

def register_table_aggregate(router: _az.Router, handler: TableAggregateHandler) -> None:
    router.register_aggregate(new_table_aggregate_dispatch(handler))

