# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/components.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.examples.v1 import table_pb2 as _m0

class TableHandSagaHandler(Protocol):
    """Strict business seam for the TableHandSaga saga."""

    def hand_started(self, event: _m0.HandStarted, dests: _az.Destinations) -> tuple[list[_t.CommandBook], list[_t.EventBook]]: ...
    def on_deal_cards_rejected(self, n: _t.Notification, rejection: _t.RejectionNotification) -> list[_t.EventBook]: ...

def new_table_hand_saga_dispatch(handler: TableHandSagaHandler) -> _az.SagaDispatch:
    dispatch = _az.SagaDispatch("TableHandSaga", "table", targets=["hand"])
    def _on_hand_started(event_any, dests):
        event = _m0.HandStarted()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.hand_started(event, dests)
    dispatch.on_event("io.angzarr.examples.v1.HandStarted", _on_hand_started)
    dispatch.on_rejected("io.angzarr.examples.v1.DealCards", handler.on_deal_cards_rejected)
    return dispatch

def register_table_hand_saga(router: _az.Router, handler: TableHandSagaHandler) -> None:
    router.register_saga(new_table_hand_saga_dispatch(handler))

