# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/components.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.examples.v1 import table_pb2 as _m0

class TablePlayerSagaHandler(Protocol):
    """Strict business seam for the TablePlayerSaga saga."""

    def hand_ended(self, event: _m0.HandEnded, dests: _az.Destinations) -> tuple[list[_t.CommandBook], list[_t.EventBook]]: ...

def new_table_player_saga_dispatch(handler: TablePlayerSagaHandler) -> _az.SagaDispatch:
    dispatch = _az.SagaDispatch("TablePlayerSaga", "table", targets=["player"])
    def _on_hand_ended(event_any, dests):
        event = _m0.HandEnded()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        return handler.hand_ended(event, dests)
    dispatch.on_event("io.angzarr.examples.v1.HandEnded", _on_hand_ended)
    return dispatch

def register_table_player_saga(router: _az.Router, handler: TablePlayerSagaHandler) -> None:
    router.register_saga(new_table_player_saga_dispatch(handler))

