# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/tournament.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.examples.v1 import tournament_pb2 as _m0

class TournamentAggregateHandler(Protocol):
    """Strict business seam for the TournamentAggregate aggregate."""

    def create_tournament(self, cmd: _m0.CreateTournament, state: _m0.TournamentState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def open_registration(self, cmd: _m0.OpenRegistration, state: _m0.TournamentState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def close_registration(self, cmd: _m0.CloseRegistration, state: _m0.TournamentState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def enroll_player(self, cmd: _m0.EnrollPlayer, state: _m0.TournamentState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def start_tournament(self, cmd: _m0.StartTournament, state: _m0.TournamentState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def complete_tournament(self, cmd: _m0.CompleteTournament, state: _m0.TournamentState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def process_rebuy(self, cmd: _m0.ProcessRebuy, state: _m0.TournamentState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def advance_blind_level(self, cmd: _m0.AdvanceBlindLevel, state: _m0.TournamentState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def eliminate_player(self, cmd: _m0.EliminatePlayer, state: _m0.TournamentState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def pause_tournament(self, cmd: _m0.PauseTournament, state: _m0.TournamentState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def resume_tournament(self, cmd: _m0.ResumeTournament, state: _m0.TournamentState, cctx: _az.CommandContext) -> Optional[_t.EventBook]: ...
    def apply_tournament_created(self, state: _m0.TournamentState, event: _m0.TournamentCreated) -> None: ...
    def apply_registration_opened(self, state: _m0.TournamentState, event: _m0.RegistrationOpened) -> None: ...
    def apply_registration_closed(self, state: _m0.TournamentState, event: _m0.RegistrationClosed) -> None: ...
    def apply_tournament_player_enrolled(self, state: _m0.TournamentState, event: _m0.TournamentPlayerEnrolled) -> None: ...
    def apply_tournament_enrollment_rejected(self, state: _m0.TournamentState, event: _m0.TournamentEnrollmentRejected) -> None: ...
    def apply_tournament_started(self, state: _m0.TournamentState, event: _m0.TournamentStarted) -> None: ...
    def apply_rebuy_processed(self, state: _m0.TournamentState, event: _m0.RebuyProcessed) -> None: ...
    def apply_rebuy_denied(self, state: _m0.TournamentState, event: _m0.RebuyDenied) -> None: ...
    def apply_blind_level_advanced(self, state: _m0.TournamentState, event: _m0.BlindLevelAdvanced) -> None: ...
    def apply_player_eliminated(self, state: _m0.TournamentState, event: _m0.PlayerEliminated) -> None: ...
    def apply_tournament_paused(self, state: _m0.TournamentState, event: _m0.TournamentPaused) -> None: ...
    def apply_tournament_resumed(self, state: _m0.TournamentState, event: _m0.TournamentResumed) -> None: ...
    def apply_tournament_completed(self, state: _m0.TournamentState, event: _m0.TournamentCompleted) -> None: ...

def new_tournament_aggregate_dispatch(handler: TournamentAggregateHandler) -> _az.AggregateDispatch:
    rebuilder = _az.Rebuilder(lambda: _m0.TournamentState())
    rebuilder.with_snapshot(lambda state, payload: state.ParseFromString(payload.value))
    def _apply_apply_tournament_created(state, payload):
        event = _m0.TournamentCreated()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_tournament_created(state, event)
    rebuilder.apply("io.angzarr.examples.v1.TournamentCreated", _apply_apply_tournament_created)
    def _apply_apply_registration_opened(state, payload):
        event = _m0.RegistrationOpened()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_registration_opened(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RegistrationOpened", _apply_apply_registration_opened)
    def _apply_apply_registration_closed(state, payload):
        event = _m0.RegistrationClosed()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_registration_closed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RegistrationClosed", _apply_apply_registration_closed)
    def _apply_apply_tournament_player_enrolled(state, payload):
        event = _m0.TournamentPlayerEnrolled()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_tournament_player_enrolled(state, event)
    rebuilder.apply("io.angzarr.examples.v1.TournamentPlayerEnrolled", _apply_apply_tournament_player_enrolled)
    def _apply_apply_tournament_enrollment_rejected(state, payload):
        event = _m0.TournamentEnrollmentRejected()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_tournament_enrollment_rejected(state, event)
    rebuilder.apply("io.angzarr.examples.v1.TournamentEnrollmentRejected", _apply_apply_tournament_enrollment_rejected)
    def _apply_apply_tournament_started(state, payload):
        event = _m0.TournamentStarted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_tournament_started(state, event)
    rebuilder.apply("io.angzarr.examples.v1.TournamentStarted", _apply_apply_tournament_started)
    def _apply_apply_rebuy_processed(state, payload):
        event = _m0.RebuyProcessed()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_rebuy_processed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RebuyProcessed", _apply_apply_rebuy_processed)
    def _apply_apply_rebuy_denied(state, payload):
        event = _m0.RebuyDenied()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_rebuy_denied(state, event)
    rebuilder.apply("io.angzarr.examples.v1.RebuyDenied", _apply_apply_rebuy_denied)
    def _apply_apply_blind_level_advanced(state, payload):
        event = _m0.BlindLevelAdvanced()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_blind_level_advanced(state, event)
    rebuilder.apply("io.angzarr.examples.v1.BlindLevelAdvanced", _apply_apply_blind_level_advanced)
    def _apply_apply_player_eliminated(state, payload):
        event = _m0.PlayerEliminated()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_player_eliminated(state, event)
    rebuilder.apply("io.angzarr.examples.v1.PlayerEliminated", _apply_apply_player_eliminated)
    def _apply_apply_tournament_paused(state, payload):
        event = _m0.TournamentPaused()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_tournament_paused(state, event)
    rebuilder.apply("io.angzarr.examples.v1.TournamentPaused", _apply_apply_tournament_paused)
    def _apply_apply_tournament_resumed(state, payload):
        event = _m0.TournamentResumed()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_tournament_resumed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.TournamentResumed", _apply_apply_tournament_resumed)
    def _apply_apply_tournament_completed(state, payload):
        event = _m0.TournamentCompleted()
        try:
            event.ParseFromString(payload.value)
        except Exception as exc:
            raise _az.any_decode_error(payload.type_url, exc)
        handler.apply_tournament_completed(state, event)
    rebuilder.apply("io.angzarr.examples.v1.TournamentCompleted", _apply_apply_tournament_completed)
    dispatch = _az.AggregateDispatch("TournamentAggregate", "tournament", rebuilder)
    def _on_create_tournament(cmd_any, state, cctx):
        cmd = _m0.CreateTournament()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.create_tournament(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.CreateTournament", _on_create_tournament)
    def _on_open_registration(cmd_any, state, cctx):
        cmd = _m0.OpenRegistration()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.open_registration(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.OpenRegistration", _on_open_registration)
    def _on_close_registration(cmd_any, state, cctx):
        cmd = _m0.CloseRegistration()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.close_registration(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.CloseRegistration", _on_close_registration)
    def _on_enroll_player(cmd_any, state, cctx):
        cmd = _m0.EnrollPlayer()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.enroll_player(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.EnrollPlayer", _on_enroll_player)
    def _on_start_tournament(cmd_any, state, cctx):
        cmd = _m0.StartTournament()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.start_tournament(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.StartTournament", _on_start_tournament)
    def _on_complete_tournament(cmd_any, state, cctx):
        cmd = _m0.CompleteTournament()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.complete_tournament(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.CompleteTournament", _on_complete_tournament)
    def _on_process_rebuy(cmd_any, state, cctx):
        cmd = _m0.ProcessRebuy()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.process_rebuy(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ProcessRebuy", _on_process_rebuy)
    def _on_advance_blind_level(cmd_any, state, cctx):
        cmd = _m0.AdvanceBlindLevel()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.advance_blind_level(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.AdvanceBlindLevel", _on_advance_blind_level)
    def _on_eliminate_player(cmd_any, state, cctx):
        cmd = _m0.EliminatePlayer()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.eliminate_player(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.EliminatePlayer", _on_eliminate_player)
    def _on_pause_tournament(cmd_any, state, cctx):
        cmd = _m0.PauseTournament()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.pause_tournament(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.PauseTournament", _on_pause_tournament)
    def _on_resume_tournament(cmd_any, state, cctx):
        cmd = _m0.ResumeTournament()
        try:
            cmd.ParseFromString(cmd_any.value)
        except Exception as exc:
            raise _az.any_decode_error(cmd_any.type_url, exc)
        return handler.resume_tournament(cmd, state, cctx)
    dispatch.on_command("io.angzarr.examples.v1.ResumeTournament", _on_resume_tournament)
    return dispatch

def register_tournament_aggregate(router: _az.Router, handler: TournamentAggregateHandler) -> None:
    router.register_aggregate(new_tournament_aggregate_dispatch(handler))

