# Code generated by angzarr codegen python. DO NOT EDIT.
# source: io/angzarr/examples/v1/projection.proto

from typing import Optional, Protocol

import angzarr_router_ffi as _az
from io.angzarr.v1 import types_pb2 as _t
from io.angzarr.examples.v1 import hand_pb2 as _m0
from io.angzarr.examples.v1 import projection_pb2 as _m1

class TrainingProjectorHandler(Protocol):
    """Strict business seam for the TrainingProjector projector."""

    def cards_dealt(self, projection: _m1.TrainingProjection, event: _m0.CardsDealt) -> None: ...
    def blind_posted(self, projection: _m1.TrainingProjection, event: _m0.BlindPosted) -> None: ...
    def action_taken(self, projection: _m1.TrainingProjection, event: _m0.ActionTaken) -> None: ...
    def betting_round_complete(self, projection: _m1.TrainingProjection, event: _m0.BettingRoundComplete) -> None: ...
    def community_cards_dealt(self, projection: _m1.TrainingProjection, event: _m0.CommunityCardsDealt) -> None: ...
    def pot_awarded(self, projection: _m1.TrainingProjection, event: _m0.PotAwarded) -> None: ...
    def hand_complete(self, projection: _m1.TrainingProjection, event: _m0.HandComplete) -> None: ...
    def finish(self, projection: _m1.TrainingProjection, events: _t.EventBook) -> _t.Projection: ...

def new_training_projector_dispatch(handler: TrainingProjectorHandler) -> _az.ProjectorDispatch:
    dispatch = _az.ProjectorDispatch("TrainingProjector", lambda: _m1.TrainingProjection())
    dispatch.for_domains("hand")
    def _on_cards_dealt(projection, event_any):
        event = _m0.CardsDealt()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.cards_dealt(projection, event)
    dispatch.on_event("io.angzarr.examples.v1.CardsDealt", _on_cards_dealt)
    def _on_blind_posted(projection, event_any):
        event = _m0.BlindPosted()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.blind_posted(projection, event)
    dispatch.on_event("io.angzarr.examples.v1.BlindPosted", _on_blind_posted)
    def _on_action_taken(projection, event_any):
        event = _m0.ActionTaken()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.action_taken(projection, event)
    dispatch.on_event("io.angzarr.examples.v1.ActionTaken", _on_action_taken)
    def _on_betting_round_complete(projection, event_any):
        event = _m0.BettingRoundComplete()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.betting_round_complete(projection, event)
    dispatch.on_event("io.angzarr.examples.v1.BettingRoundComplete", _on_betting_round_complete)
    def _on_community_cards_dealt(projection, event_any):
        event = _m0.CommunityCardsDealt()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.community_cards_dealt(projection, event)
    dispatch.on_event("io.angzarr.examples.v1.CommunityCardsDealt", _on_community_cards_dealt)
    def _on_pot_awarded(projection, event_any):
        event = _m0.PotAwarded()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.pot_awarded(projection, event)
    dispatch.on_event("io.angzarr.examples.v1.PotAwarded", _on_pot_awarded)
    def _on_hand_complete(projection, event_any):
        event = _m0.HandComplete()
        try:
            event.ParseFromString(event_any.value)
        except Exception as exc:
            raise _az.any_decode_error(event_any.type_url, exc)
        handler.hand_complete(projection, event)
    dispatch.on_event("io.angzarr.examples.v1.HandComplete", _on_hand_complete)
    dispatch.finish(handler.finish)
    return dispatch

def register_training_projector(router: _az.Router, handler: TrainingProjectorHandler) -> None:
    router.register_projector(new_training_projector_dispatch(handler))

