# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/angzarr/v1/options.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'io/angzarr/v1/options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bio/angzarr/v1/options.proto\x12\rio.angzarr.v1\x1a google/protobuf/descriptor.proto\"\xc2\x01\n\x10\x43omponentOptions\x12\x30\n\x04kind\x18\x01 \x01(\x0e\x32\x1c.io.angzarr.v1.ComponentKindR\x04kind\x12!\n\x0cinput_domain\x18\x02 \x01(\tR\x0binputDomain\x12#\n\routput_domain\x18\x03 \x01(\tR\x0coutputDomain\x12\x12\n\x04name\x18\x04 \x01(\tR\x04name\x12 \n\x0b\x63ompensates\x18\x05 \x03(\tR\x0b\x63ompensates\"D\n\x0e\x43ommandOptions\x12\x1c\n\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x14\n\x05\x65mits\x18\x02 \x03(\tR\x05\x65mits\"_\n\rEventConsumer\x12\x1c\n\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x16\n\x06\x64omain\x18\x02 \x01(\tR\x06\x64omain\x12\x18\n\x07\x61pplies\x18\x03 \x01(\x08R\x07\x61pplies*\xa8\x01\n\rComponentKind\x12\x1e\n\x1a\x43OMPONENT_KIND_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x43OMPONENT_KIND_AGGREGATE\x10\x01\x12\x17\n\x13\x43OMPONENT_KIND_SAGA\x10\x02\x12\"\n\x1e\x43OMPONENT_KIND_PROCESS_MANAGER\x10\x03\x12\x1c\n\x18\x43OMPONENT_KIND_PROJECTOR\x10\x04:`\n\tcomponent\x12\x1f.google.protobuf.MessageOptions\x18\xb4\x87\x03 \x01(\x0b\x32\x1f.io.angzarr.v1.ComponentOptionsR\tcomponent:Z\n\x07\x63ommand\x12\x1f.google.protobuf.MessageOptions\x18\xb8\x87\x03 \x01(\x0b\x32\x1d.io.angzarr.v1.CommandOptionsR\x07\x63ommand:U\n\x05\x65vent\x12\x1f.google.protobuf.MessageOptions\x18\xb9\x87\x03 \x03(\x0b\x32\x1c.io.angzarr.v1.EventConsumerR\x05\x65ventB\xa0\x01\n\x11\x63om.io.angzarr.v1B\x0cOptionsProtoP\x01Z\'examples/v2/gen/io/angzarr/v1;angzarrv1\xa2\x02\x03IAX\xaa\x02\rIo.Angzarr.V1\xca\x02\rIo\\Angzarr\\V1\xe2\x02\x19Io\\Angzarr\\V1\\GPBMetadata\xea\x02\x0fIo::Angzarr::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.angzarr.v1.options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.io.angzarr.v1B\014OptionsProtoP\001Z\'examples/v2/gen/io/angzarr/v1;angzarrv1\242\002\003IAX\252\002\rIo.Angzarr.V1\312\002\rIo\\Angzarr\\V1\342\002\031Io\\Angzarr\\V1\\GPBMetadata\352\002\017Io::Angzarr::V1'
  _globals['_COMPONENTKIND']._serialized_start=445
  _globals['_COMPONENTKIND']._serialized_end=613
  _globals['_COMPONENTOPTIONS']._serialized_start=81
  _globals['_COMPONENTOPTIONS']._serialized_end=275
  _globals['_COMMANDOPTIONS']._serialized_start=277
  _globals['_COMMANDOPTIONS']._serialized_end=345
  _globals['_EVENTCONSUMER']._serialized_start=347
  _globals['_EVENTCONSUMER']._serialized_end=442
# @@protoc_insertion_point(module_scope)
