# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/angzarr/v1/projector.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'io/angzarr/v1/projector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from io.angzarr.v1 import types_pb2 as io_dot_angzarr_dot_v1_dot_types__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dio/angzarr/v1/projector.proto\x12\rio.angzarr.v1\x1a\x19io/angzarr/v1/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"M\n\x19SpeculateProjectorRequest\x12\x30\n\x06\x65vents\x18\x01 \x01(\x0b\x32\x18.io.angzarr.v1.EventBookR\x06\x65vents2\x9b\x01\n\x10ProjectorService\x12=\n\x06Handle\x12\x18.io.angzarr.v1.EventBook\x1a\x19.io.angzarr.v1.Projection\x12H\n\x11HandleSpeculative\x12\x18.io.angzarr.v1.EventBook\x1a\x19.io.angzarr.v1.Projection2\xd8\x02\n\x1bProjectorCoordinatorService\x12\x63\n\nHandleSync\x12\x1b.io.angzarr.v1.EventRequest\x1a\x19.io.angzarr.v1.Projection\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x12/v1/projector/sync:\x01*\x12T\n\x06Handle\x12\x18.io.angzarr.v1.EventBook\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12\"\r/v1/projector:\x01*\x12~\n\x11HandleSpeculative\x12(.io.angzarr.v1.SpeculateProjectorRequest\x1a\x19.io.angzarr.v1.Projection\"$\x82\xd3\xe4\x93\x02\x1e\"\x19/v1/projector/speculative:\x01*B\xa2\x01\n\x11\x63om.io.angzarr.v1B\x0eProjectorProtoP\x01Z\'examples/v2/gen/io/angzarr/v1;angzarrv1\xa2\x02\x03IAX\xaa\x02\rIo.Angzarr.V1\xca\x02\rIo\\Angzarr\\V1\xe2\x02\x19Io\\Angzarr\\V1\\GPBMetadata\xea\x02\x0fIo::Angzarr::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.angzarr.v1.projector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.io.angzarr.v1B\016ProjectorProtoP\001Z\'examples/v2/gen/io/angzarr/v1;angzarrv1\242\002\003IAX\252\002\rIo.Angzarr.V1\312\002\rIo\\Angzarr\\V1\342\002\031Io\\Angzarr\\V1\\GPBMetadata\352\002\017Io::Angzarr::V1'
  _globals['_PROJECTORCOORDINATORSERVICE'].methods_by_name['HandleSync']._loaded_options = None
  _globals['_PROJECTORCOORDINATORSERVICE'].methods_by_name['HandleSync']._serialized_options = b'\202\323\344\223\002\027\"\022/v1/projector/sync:\001*'
  _globals['_PROJECTORCOORDINATORSERVICE'].methods_by_name['Handle']._loaded_options = None
  _globals['_PROJECTORCOORDINATORSERVICE'].methods_by_name['Handle']._serialized_options = b'\202\323\344\223\002\022\"\r/v1/projector:\001*'
  _globals['_PROJECTORCOORDINATORSERVICE'].methods_by_name['HandleSpeculative']._loaded_options = None
  _globals['_PROJECTORCOORDINATORSERVICE'].methods_by_name['HandleSpeculative']._serialized_options = b'\202\323\344\223\002\036\"\031/v1/projector/speculative:\001*'
  _globals['_SPECULATEPROJECTORREQUEST']._serialized_start=134
  _globals['_SPECULATEPROJECTORREQUEST']._serialized_end=211
  _globals['_PROJECTORSERVICE']._serialized_start=214
  _globals['_PROJECTORSERVICE']._serialized_end=369
  _globals['_PROJECTORCOORDINATORSERVICE']._serialized_start=372
  _globals['_PROJECTORCOORDINATORSERVICE']._serialized_end=716
# @@protoc_insertion_point(module_scope)
