# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/angzarr/v1/query.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'io/angzarr/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from io.angzarr.v1 import types_pb2 as io_dot_angzarr_dot_v1_dot_types__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19io/angzarr/v1/query.proto\x12\rio.angzarr.v1\x1a\x19io/angzarr/v1/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto2\x99\x03\n\x11\x45ventQueryService\x12g\n\x0cGetEventBook\x12\x14.io.angzarr.v1.Query\x1a\x18.io.angzarr.v1.EventBook\"\'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/query/{cover.domain}/events\x12m\n\tGetEvents\x12\x14.io.angzarr.v1.Query\x1a\x18.io.angzarr.v1.EventBook\".\x82\xd3\xe4\x93\x02(\x12&/v1/query/{cover.domain}/events/stream0\x01\x12\x41\n\x0bSynchronize\x12\x14.io.angzarr.v1.Query\x1a\x18.io.angzarr.v1.EventBook(\x01\x30\x01\x12i\n\x11GetAggregateRoots\x12\x16.google.protobuf.Empty\x1a\x1c.io.angzarr.v1.AggregateRoot\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/query/aggregates0\x01\x42\x9e\x01\n\x11\x63om.io.angzarr.v1B\nQueryProtoP\x01Z\'examples/v2/gen/io/angzarr/v1;angzarrv1\xa2\x02\x03IAX\xaa\x02\rIo.Angzarr.V1\xca\x02\rIo\\Angzarr\\V1\xe2\x02\x19Io\\Angzarr\\V1\\GPBMetadata\xea\x02\x0fIo::Angzarr::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.angzarr.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.io.angzarr.v1B\nQueryProtoP\001Z\'examples/v2/gen/io/angzarr/v1;angzarrv1\242\002\003IAX\252\002\rIo.Angzarr.V1\312\002\rIo\\Angzarr\\V1\342\002\031Io\\Angzarr\\V1\\GPBMetadata\352\002\017Io::Angzarr::V1'
  _globals['_EVENTQUERYSERVICE'].methods_by_name['GetEventBook']._loaded_options = None
  _globals['_EVENTQUERYSERVICE'].methods_by_name['GetEventBook']._serialized_options = b'\202\323\344\223\002!\022\037/v1/query/{cover.domain}/events'
  _globals['_EVENTQUERYSERVICE'].methods_by_name['GetEvents']._loaded_options = None
  _globals['_EVENTQUERYSERVICE'].methods_by_name['GetEvents']._serialized_options = b'\202\323\344\223\002(\022&/v1/query/{cover.domain}/events/stream'
  _globals['_EVENTQUERYSERVICE'].methods_by_name['GetAggregateRoots']._loaded_options = None
  _globals['_EVENTQUERYSERVICE'].methods_by_name['GetAggregateRoots']._serialized_options = b'\202\323\344\223\002\026\022\024/v1/query/aggregates'
  _globals['_EVENTQUERYSERVICE']._serialized_start=131
  _globals['_EVENTQUERYSERVICE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
