# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/angzarr/v1/stream.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'io/angzarr/v1/stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from io.angzarr.v1 import types_pb2 as io_dot_angzarr_dot_v1_dot_types__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aio/angzarr/v1/stream.proto\x12\rio.angzarr.v1\x1a\x19io/angzarr/v1/types.proto\x1a\x1cgoogle/api/annotations.proto2\x84\x01\n\x12\x45ventStreamService\x12n\n\tSubscribe\x12 .io.angzarr.v1.EventStreamFilter\x1a\x18.io.angzarr.v1.EventBook\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/stream/{correlation_id}0\x01\x42\x9f\x01\n\x11\x63om.io.angzarr.v1B\x0bStreamProtoP\x01Z\'examples/v2/gen/io/angzarr/v1;angzarrv1\xa2\x02\x03IAX\xaa\x02\rIo.Angzarr.V1\xca\x02\rIo\\Angzarr\\V1\xe2\x02\x19Io\\Angzarr\\V1\\GPBMetadata\xea\x02\x0fIo::Angzarr::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.angzarr.v1.stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.io.angzarr.v1B\013StreamProtoP\001Z\'examples/v2/gen/io/angzarr/v1;angzarrv1\242\002\003IAX\252\002\rIo.Angzarr.V1\312\002\rIo\\Angzarr\\V1\342\002\031Io\\Angzarr\\V1\\GPBMetadata\352\002\017Io::Angzarr::V1'
  _globals['_EVENTSTREAMSERVICE'].methods_by_name['Subscribe']._loaded_options = None
  _globals['_EVENTSTREAMSERVICE'].methods_by_name['Subscribe']._serialized_options = b'\202\323\344\223\002\035\022\033/v1/stream/{correlation_id}'
  _globals['_EVENTSTREAMSERVICE']._serialized_start=103
  _globals['_EVENTSTREAMSERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
