# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/angzarr/v1/upcaster.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'io/angzarr/v1/upcaster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from io.angzarr.v1 import types_pb2 as io_dot_angzarr_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cio/angzarr/v1/upcaster.proto\x12\rio.angzarr.v1\x1a\x19io/angzarr/v1/types.proto\"Y\n\rUpcastRequest\x12\x16\n\x06\x64omain\x18\x01 \x01(\tR\x06\x64omain\x12\x30\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x18.io.angzarr.v1.EventPageR\x06\x65vents\"B\n\x0eUpcastResponse\x12\x30\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x18.io.angzarr.v1.EventPageR\x06\x65vents2X\n\x0fUpcasterService\x12\x45\n\x06Upcast\x12\x1c.io.angzarr.v1.UpcastRequest\x1a\x1d.io.angzarr.v1.UpcastResponseB\xa1\x01\n\x11\x63om.io.angzarr.v1B\rUpcasterProtoP\x01Z\'examples/v2/gen/io/angzarr/v1;angzarrv1\xa2\x02\x03IAX\xaa\x02\rIo.Angzarr.V1\xca\x02\rIo\\Angzarr\\V1\xe2\x02\x19Io\\Angzarr\\V1\\GPBMetadata\xea\x02\x0fIo::Angzarr::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.angzarr.v1.upcaster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.io.angzarr.v1B\rUpcasterProtoP\001Z\'examples/v2/gen/io/angzarr/v1;angzarrv1\242\002\003IAX\252\002\rIo.Angzarr.V1\312\002\rIo\\Angzarr\\V1\342\002\031Io\\Angzarr\\V1\\GPBMetadata\352\002\017Io::Angzarr::V1'
  _globals['_UPCASTREQUEST']._serialized_start=74
  _globals['_UPCASTREQUEST']._serialized_end=163
  _globals['_UPCASTRESPONSE']._serialized_start=165
  _globals['_UPCASTRESPONSE']._serialized_end=231
  _globals['_UPCASTERSERVICE']._serialized_start=233
  _globals['_UPCASTERSERVICE']._serialized_end=321
# @@protoc_insertion_point(module_scope)
